apiVersion: v1
kind: Service
metadata:
  name: {{ include "oracle-relayer.fullname" . }}
  labels:
    {{- include "oracle-relayer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8185
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "oracle-relayer.selectorLabels" . | nindent 4 }}
