apiVersion: v1
kind: Service
metadata:
  name: {{ include "bc.fullname" . }}
  labels:
    {{- include "bc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 26657
      targetPort: 26657
      protocol: TCP
      name: http
    - port: 26658
      targetPort: 26658
      protocol: TCP
      name: abci
    - port: 26656
      targetPort: 26656
      protocol: TCP
      name: tcp
    - port: 26656
      targetPort: 26656
      protocol: UDP
      name: udp
  selector:
    {{- include "bc.selectorLabels" . | nindent 4 }}
