apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "bc.fullname" . }}
  labels:
    {{- include "bc.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bc.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "bc.fullname" . }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bc.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bc.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: install
          image: busybox
          command:
            ['sh', '-c', "echo '{\"height\": \"0\",\"round\": \"0\",\"step\": 0}' > /data/data/priv_validator_state.json"]
          volumeMounts:
            - name: data
              mountPath: /data/data
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 26657
              protocol: TCP
            - name: abci
              containerPort: 26658
              protocol: TCP
            - name: udp
              containerPort: 26656
              protocol: UDP
            - name: tcp
              containerPort: 26656
              protocol: TCP
          volumeMounts:
            - name: secret-volume
              mountPath: /data/config/node_key.json
              subPath: node_key.json
              readOnly: true
            - name: secret-volume
              mountPath: /data/config/priv_validator_key.json
              subPath: priv_validator_key.json
              readOnly: true
            - name: config-volume
              mountPath: /data/config/app.toml
              subPath: app.toml
              readOnly: true
            - name: config-volume
              mountPath: /data/config/config.toml
              subPath: config.toml
              readOnly: true
            - name: config-volume
              mountPath: /data/config/genesis.json
              subPath: genesis.json
              readOnly: true
            - name: data
              mountPath: /data/data
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Values.configName }}
        - name: secret-volume
          secret:
            secretName: {{ .Values.secretName }}
        - name: data
          {{ if .Values.persistHost }}
          hostPath:
            path: {{ .Values.persistHost }}
          {{ else }}
          emptyDir: {}
          {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
